"""Initial migration

Revision ID: 44ea97b0e6d1
Revises: 
Create Date: 2025-03-26 15:29:20.872921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ea97b0e6d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tron_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=34), nullable=False),
    sa.Column('bandwidth', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('balance_trx', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tron_addresses_address'), 'tron_addresses', ['address'], unique=True)
    op.create_index(op.f('ix_tron_addresses_id'), 'tron_addresses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tron_addresses_id'), table_name='tron_addresses')
    op.drop_index(op.f('ix_tron_addresses_address'), table_name='tron_addresses')
    op.drop_table('tron_addresses')
    # ### end Alembic commands ###
